### PR TITLE
Fast python decoder for frames and python bindings

### PR DESCRIPTION
**Pull request by jmcarcell**
This PR adds:

- Python decoders that are 100-150 times faster (for a Fragment containing 8192 `WIBFrames`) than getting each frame and then putting all of them in a numpy array . This decoder puts the result in a numpy array directly, it works both for frames and for timestamps with separate functions for each
- A script to test the speed and correctness of this python decoder
- Similar decoders for `WIB2Frames` and `DAPHNEFrames` since the data types are kind of similar, these are untested but they are almost identical to the WIBFrames one
- Python bindings for `WIB2Frames` and `DAPHNEFrames` (I needed those for the decoders)

### CODE REVIEW

**Comment by alessandrothea** [comment]
Hi @jmcarcell,

Thank you for this nice PR. It's going to make a big difference.
The bulk of the code looks good, but before the PR can be merged, there are a few changes required at the level of naming convention, methods and file organisation and to ensure that the interface is clear.

1) The use of the name `Decoder` is confusing. The functions you implemented don't decode a single frame (or waveforms) but blocks of them. A better name should be used to represent that these are block unpackers.

2) Similarly `numpy_decoder` and `numpy_timestamps` are confusing. `numpy` can be associated to many things, not just arrays. 
   * `decoder` should be replaced with `adcs` or similar
   * Also, they are utilities and not well suited as methods. 
 
3) The `*Decoder.hpp` headers
   * Are python binding specific and not public. They should be moved to `pybindsrc`
   * Contain the function implementation, the must be moved to a separate .cc file
   
4) The test scripts are supposed to be located in `test/scripts`. Please move `wibdecoder.py` there

This should be all...

**Comment by jmcarcell** [comment]
I've addressed all the comments but this one:

> Also, they are utilities and not well suited as methods.

How do you want to call them? I find the current way convenient:
```
>>> import detdataformats
>>> from detdataformats.wib import np_array_adc
>>> np_array_adc
<built-in method np_array_adc of PyCapsule object at 0x7f7d6267c780>
```

I realized that most of the cases are going to be unpacking a full Fragment and not only part of it so I added functions to unpack the whole Fragment while the other ones are still accessible. My proposal would be:

- `np_array_adc` for unpacking the whole Fragment, gets the Fragment as input
- `np_array_timestamp` the same as above but for the timestamp
-  `np_array_adc_data` this is the original version, gets a pointer to the data and the number of frames one wants to unpack
-  `np_array_timestamp_data` same as above for timestamps

The last two probably have a long name but I expect the first two to be used in most cases, I thought `np_adc` was not too descriptive but I don't have any strong preferences

**Comment by alessandrothea** [comment]
> I've addressed all the comments but this one:

Thanks!
> > Also, they are utilities and not well suited as methods.
> 
> How do you want to call them? I find the current way convenient:
> 
> ```
> >>> import detdataformats
> >>> from detdataformats.wib import np_array_adc
> >>> np_array_adc
> <built-in method np_array_adc of PyCapsule object at 0x7f7d6267c780>
> ```

Apologies, I misread the code. I thought these functions were added to the Frame classes, while they simply registered with the module. That is fine. Regarding the names `np_array_adc` is already better. I'll have a think if something even more explicit comes to my mind.


> I realized that most of the cases are going to be unpacking a full Fragment and not only part of it so I added functions to unpack the whole Fragment while the other ones are still accessible. My proposal would be:
> 
> * `np_array_adc` for unpacking the whole Fragment, gets the Fragment as input
> * `np_array_timestamp` the same as above but for the timestamp
> * `np_array_adc_data` this is the original version, gets a pointer to the data and the number of frames one wants to unpack
> * `np_array_timestamp_data` same as above for timestamps
> 
> The last two probably have a long name but I expect the first two to be used in most cases, I thought `np_adc` was not too descriptive but I don't have any strong preferences

Indeed, but there's a catch. Having `np_array_adc` unpacking a fragment introduces a dependency on `daqdataformats` which violates the requirement not to have mutual dependencies between the two packages. 
We definitely want such a utility but it must live in a third package. I started putting one together before Xmas, 
https://github.com/DUNE-DAQ/rawdatautils
but never got to the point to commit anything. You beat me to it :)

Bottomline: `detdataformats` must have no dependencies on other packages. Helper functions that simplify the unpacking of detector data blocks can only rely on bare pointers, if they are part of this package. Otherwise they shall be committed to 
`rawdatautils`

**Comment by jmcarcell** [comment]
Ok, I changed the name to `np_array_adc/timestamp` for the functions and remove the ones that depended on daqdataformats

**Comment by jmcarcell** [comment]
The implementation would be a bit convoluted having the unpackers that take data pointers and the unpackers that can unpack a whole fragment in different places so it was agreed to have them both in the same place: https://github.com/DUNE-DAQ/rawdatautils/pull/1
I'm closing this PR but there are some python bindings for the other formats in this PR (that are not in the `rawdatautils` PR) that I'll recover and make a PR with them

**Pull request closed without merging**
